# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id_alamat', models.AutoField(db_column='ID_ALAMAT', primary_key=True, serialize=False)),
                ('alamat_lengkap', models.CharField(db_column='ALAMAT_LENGKAP', max_length=150, unique=True)),
                ('kode_pos', models.CharField(db_column='KODE_POS', max_length=5)),
            ],
            options={
                'db_table': 'alamat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barangpesanan',
            fields=[
                ('id_barang_pesanan', models.AutoField(db_column='ID_BARANG_PESANAN', primary_key=True, serialize=False)),
                ('kuantitas', models.DecimalField(db_column='KUANTITAS', decimal_places=0, max_digits=8)),
            ],
            options={
                'db_table': 'barangpesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DaftarKeinginan',
            fields=[
                ('id_daftar_keinginan', models.AutoField(db_column='ID_DAFTAR_KEINGINAN', primary_key=True, serialize=False)),
                ('tanggal_terdaftar', models.DateTimeField(db_column='TANGGAL_TERDAFTAR')),
            ],
            options={
                'db_table': 'daftar_keinginan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dikategorikan',
            fields=[
                ('id_pengategorian', models.AutoField(db_column='ID_PENGATEGORIAN', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dikategorikan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historydiskon',
            fields=[
                ('id_diskon', models.AutoField(db_column='ID_DISKON', primary_key=True, serialize=False)),
                ('waktu_diskon', models.DateTimeField(db_column='WAKTU_DISKON')),
                ('besar_diskon', models.DecimalField(db_column='BESAR_DISKON', decimal_places=0, max_digits=8)),
            ],
            options={
                'db_table': 'historydiskon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historyharga',
            fields=[
                ('id_harga', models.AutoField(db_column='ID_HARGA', primary_key=True, serialize=False)),
                ('waktuharga', models.DateTimeField(db_column='WAKTUHARGA')),
                ('harga', models.DecimalField(db_column='HARGA', decimal_places=0, max_digits=8)),
            ],
            options={
                'db_table': 'historyharga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('kode_kategori', models.CharField(db_column='KODE_KATEGORI', max_length=5, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(db_column='NAMA_KATEGORI', max_length=20)),
            ],
            options={
                'db_table': 'kategori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('kode_kecamatan', models.IntegerField(db_column='KODE_KECAMATAN', primary_key=True, serialize=False)),
                ('nama_kecamatan', models.CharField(db_column='NAMA_KECAMATAN', max_length=30)),
            ],
            options={
                'db_table': 'kecamatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('kode_kota', models.IntegerField(db_column='KODE_KOTA', primary_key=True, serialize=False)),
                ('nama_kota', models.CharField(db_column='NAMA_KOTA', max_length=30)),
            ],
            options={
                'db_table': 'kota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Merek',
            fields=[
                ('kode_merek', models.CharField(db_column='KODE_MEREK', max_length=5, primary_key=True, serialize=False)),
                ('nama_merek', models.CharField(db_column='NAMA_MEREK', max_length=20)),
            ],
            options={
                'db_table': 'merek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('nama_lengkap', models.CharField(db_column='NAMA_LENGKAP', max_length=50)),
                ('tanggal_lahir', models.DateField(db_column='TANGGAL_LAHIR')),
                ('nomor_hp', models.CharField(db_column='NOMOR_HP', max_length=12)),
                ('email', models.CharField(db_column='EMAIL', max_length=50, primary_key=True, serialize=False)),
                ('kata_sandi', models.CharField(db_column='KATA_SANDI', max_length=50)),
            ],
            options={
                'db_table': 'pelanggan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('kode_pembayaran', models.CharField(db_column='KODE_PEMBAYARAN', max_length=12, primary_key=True, serialize=False)),
                ('waktu_pembayaran', models.DateTimeField(db_column='WAKTU_PEMBAYARAN')),
                ('total_belanja', models.DecimalField(db_column='TOTAL_BELANJA', decimal_places=0, max_digits=8)),
                ('status_pembayaran', models.IntegerField(blank=True, db_column='STATUS_PEMBAYARAN', null=True)),
            ],
            options={
                'db_table': 'pembayaran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('kode_pengiriman', models.CharField(db_column='KODE_PENGIRIMAN', max_length=10, primary_key=True, serialize=False)),
                ('tanggal_kirim', models.DateField(db_column='TANGGAL_KIRIM')),
                ('tanggal_terima', models.DateField(db_column='TANGGAL_TERIMA')),
                ('nama_pengirim', models.CharField(db_column='NAMA_PENGIRIM', max_length=50)),
                ('nama_penerima', models.CharField(db_column='NAMA_PENERIMA', max_length=50)),
            ],
            options={
                'db_table': 'pengiriman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('kode_pesanan', models.CharField(db_column='KODE_PESANAN', max_length=15, primary_key=True, serialize=False)),
                ('waktu_pesanan', models.DateTimeField(db_column='WAKTU_PESANAN')),
            ],
            options={
                'db_table': 'pesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('kode_produk', models.CharField(db_column='KODE_PRODUK', max_length=10, primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(db_column='NAMA_PRODUK', max_length=50)),
                ('material', models.CharField(blank=True, db_column='MATERIAL', max_length=50, null=True)),
                ('deskripsi_produk', models.CharField(blank=True, db_column='DESKRIPSI_PRODUK', max_length=500, null=True)),
                ('negara_pemroduksi', models.CharField(blank=True, db_column='NEGARA_PEMRODUKSI', max_length=30, null=True)),
                ('gambar', models.TextField(blank=True, db_column='GAMBAR', null=True)),
                ('stok', models.DecimalField(db_column='STOK', decimal_places=0, max_digits=8)),
            ],
            options={
                'db_table': 'produk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('kode_provinsi', models.IntegerField(db_column='KODE_PROVINSI', primary_key=True, serialize=False)),
                ('nama_provinsi', models.CharField(db_column='NAMA_PROVINSI', max_length=30)),
            ],
            options={
                'db_table': 'provinsi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(db_column='ID_REVIEW', primary_key=True, serialize=False)),
                ('email_review', models.CharField(db_column='EMAIL_REVIEW', max_length=50)),
                ('judul_review', models.CharField(db_column='JUDUL_REVIEW', max_length=100)),
                ('isi', models.CharField(db_column='ISI', max_length=300)),
                ('rating_kualitas', models.DecimalField(blank=True, db_column='RATING_KUALITAS', decimal_places=0, max_digits=8, null=True)),
                ('rating_tampilan', models.DecimalField(blank=True, db_column='RATING_TAMPILAN', decimal_places=0, max_digits=8, null=True)),
                ('rating_harga', models.DecimalField(blank=True, db_column='RATING_HARGA', decimal_places=0, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
